[build]
  command = "npm run build"
  publish = ".output/public"
  functions = ".netlify/functions-internal"

[build.environment]
  NODE_VERSION = "18"
  NITRO_PRESET = "netlify"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
